<?php defined('SYSPATH') or die('No direct access allowed.');

print(Kohana::FILE_SECURITY."\n\n");

print("// This file was generated by Kohana-I18nget, http://github.com/rafsoaken/kohana-i18nget\n\n");

print("return array(\n");

//load existing translation table - need that to check for keys that equal their translations
$table = I18n::load($language_code);

foreach ($data as $file)
{
	print("\t// ".$file['filepath_human']."\n");

	foreach ($file['lines'] as $line)
	{
		$line['line_string'] = str_replace('<?php', '', $line['line_string']);
		$line['line_string'] = str_replace('<?', '', $line['line_string']);
		$line['line_string'] = str_replace('?>', '', $line['line_string']);
		$line['line_string'] = trim($line['line_string']);

		foreach ($line['phrases'] as $phrase)
		{
			$phrase_fixed = str_replace('\\\'', '\'', $phrase);
			$phrase_fixed = str_replace('\\"', '"', $phrase_fixed);


            if( $global_i18n )
            {
                //I18n::get() doesnt tell us if the key is equal to the translation
        	    $phrase_translated = Arr::get($table, $phrase_fixed, NULL);
            }
            else
            {
                $phrase_translated = Arr::get( file_exists( $filename ) ?
                    Kohana::load($filename) : array(), $phrase_fixed, NULL);
            }

			$phrase_translated_fixed = str_replace('\'', '\\\'', (string)$phrase_translated);

			$not_translated = '';

			if ( is_null($phrase_translated) )
			{
				$not_translated = '/// TODO';
				$phrase_translated_fixed = '';
			}

// 			print($not_translated."\t'$phrase' => '".$phrase_translated_fixed."', // ".$line['line_number'].": ".$line['line_string']."\n");
			print($not_translated."\t'$phrase' => '".$phrase_translated_fixed."', // ".$line['line_number']."\n");
		}
	}

	print("\n");
}

// Orphan phrases
print("\t// Orphan phrases\n");

foreach ($orphe_phrases as $phrase)
{
    if( $global_i18n )
    {
        //I18n::get() doesnt tell us if the key is equal to the translation
	    $phrase_translated = Arr::get($table, $phrase, NULL);
    }
    else
    {
        $phrase_translated = Arr::get( file_exists( $filename ) ?
            Kohana::load($filename) : array(), $phrase, NULL);
    }

	$not_translated = '';

	if ( is_null($phrase_translated) )
	{
		$not_translated = '/// TODO';
		$phrase_translated = '';
	}

	print($not_translated."\t'$phrase' => '".$phrase_translated."',\n");
}
print(");\n");