<?php defined('SYSPATH') or die('No direct script access.');

// This file was generated by Kohana-I18nget, http://github.com/rafsoaken/kohana-i18nget

return array(
	// bootstrap.php
/// TODO	'Feowl empowers local media and their stakeholders with accurate and actionable insights on the electricity supply' => '', // 130
/// TODO	'feowl, foewl, empowers, power, cut, power cut, accurate, accuration, insights, insight, pool, electricity, cameroon, africa, supply' => '', // 133

	// views/explore.tpl
/// TODO	'Explore the data collected by Feowl' => '', // 9
/// TODO	'Legend' => '', // 17
/// TODO	'No relevant data' => '', // 19
/// TODO	'Low power cuts' => '', // 20
/// TODO	'High power cuts' => '', // 21
/// TODO	'User reports' => '', // 30
/// TODO	'District' => '', // 34
/// TODO	'Duration' => '', // 35
/// TODO	'Date' => '', // 36
/// TODO	'Quality' => '', // 37
/// TODO	'Loading' => '', // 50
/// TODO	'Load more' => '', // 73
/// TODO	'No reports submited for that period' => '', // 82

	// views/welcome.tpl
/// TODO	'Welcome to Feowl' => '', // 27

	// views/layout/footer.tpl
/// TODO	'Fork us on GitHub!' => '', // 9
/// TODO	'Feowl files under an Apache licence' => '', // 10
/// TODO	'contact'}</a> | <a href="http://feowl.tumblr.com/">{__ t='blog' => '', // 14
/// TODO	'Feowl is financed by the <a href="http://www.freemedia.at/">International Press Institute</a>.' => '', // 18
/// TODO	'It\'s a project by <a href="http://www.internetsansfrontieres.com/">Internet Sans Frontières</a>, <a href="http://jplusplus.org/">Journalism++</a>, <a href="http://www.tesobe.com/">Tesobe</a> and <a href="http://www.wasamundi.com/">Wasamundi</a>.' => '', // 21

	// views/layout/menu.tpl
/// TODO	'Account' => '', // 16
/// TODO	'Profile' => '', // 21
/// TODO	'Sign Out' => '', // 23
/// TODO	'Language' => '', // 29
/// TODO	'Home' => '', // 58
/// TODO	'Explore' => '', // 59
/// TODO	'Contribute' => '', // 60

	// Orphan phrases
	'User Guide' => 'Guide Utilisateur',
);
