<?php defined('SYSPATH') or die('No direct script access.');

// This file was generated by Kohana-I18nget, http://github.com/rafsoaken/kohana-i18nget

return array(
	// bootstrap.php
/// TODO	'Feowl empowers local media and their stakeholders with accurate and actionable insights on the electricity supply' => '', // 130
/// TODO	'feowl, foewl, empowers, power, cut, power cut, accurate, accuration, insights, insight, pool, electricity, cameroon, africa, supply' => '', // 133

	// views/explore.tpl
	'Explore the data collected by Feowl' => 'Explorez les données collectées par Feowl', // 9
	'Legend' => 'Légende', // 17
/// TODO	'No relevant data' => '', // 19
/// TODO	'Low power cuts' => '', // 20
/// TODO	'High power cuts' => '', // 21
	'User reports' => 'Rapports des utilisateurs', // 30
	'District' => 'Arrondissement', // 34
	'Duration' => 'Durée', // 35
	'Date' => 'Date', // 36
	'Quality' => 'Qualité', // 37
	'Loading' => 'Chargement', // 50
	'Load more' => 'Voir plus', // 73
	'No reports submited for that period' => 'Aucun rapport soumis durant cette période', // 82

	// views/welcome.tpl
	'Welcome to Feowl' => 'Bienvenue sur Feowl	', // 27

	// views/layout/footer.tpl
	'Fork us on GitHub!' => 'Cloner sur GitHub!', // 9
	'Feowl files under an Apache licence' => 'Le code source de Feowl est sous licence Apache', // 10
	'contact' => 'contact', // 14
	'blog' => 'blog', // 14
	'Feowl is financed by the <a href="http://www.freemedia.at/">International Press Institute</a>.' => 'Feowl est financé par le <a href="http://www.freemedia.at/">International Press Institute</a>.', // 18
	'It\'s a project by <a href="http://www.internetsansfrontieres.com/">Internet Sans Frontières</a>, <a href="http://jplusplus.org/">Journalism++</a>, <a href="http://www.tesobe.com/">Tesobe</a> and <a href="http://www.wasamundi.com/">Wasamundi</a>.' => 'Ce projet est mené  par <a href="http://www.internetsansfrontieres.com/">Internet Sans Frontières</a>, <a href="http://jplusplus.org/">Journalism++</a>, <a href="http://www.tesobe.com/">Tesobe</a> et <a href="http://www.wasamundi.com/">Wasamundi</a>.', // 21

	// views/layout/menu.tpl
	'Account' => 'Acompte', // 16
	'Profile' => 'Profil', // 21
	'Sign Out' => 'Déconnexion', // 23
	'Language' => 'Langue', // 29
	'Home' => 'Accueil', // 58
	'Explore' => 'Explorer', // 59
	'Contribute' => 'Contribuer', // 60

	// Orphan phrases
	'User Guide' => 'Guide Utilisateur',
);
