<?php defined('SYSPATH') or die('No direct script access.');

// This file was generated by Kohana-I18nget, http://github.com/rafsoaken/kohana-i18nget

return array(
	// bootstrap.php
/// TODO	'Feowl empowers local media and their stakeholders with accurate and actionable insights on the electricity supply' => '', // 130
/// TODO	'feowl, foewl, empowers, power, cut, power cut, accurate, accuration, insights, insight, pool, electricity, cameroon, africa, supply' => '', // 133

	// views/user/login_info.tpl
/// TODO	'Login' => '', // 1
/// TODO	'Login and report power cuts' => '', // 1
/// TODO	'Feowl team.' => '', // 1

	// views/user/login.tpl
/// TODO	'Email' => '', // 14
/// TODO	'Password' => '', // 21

	// views/user/signup_info.tpl
/// TODO	'Sign Up' => '', // 1
/// TODO	'Don\'t worry, they will not contradict you when i finish with your report and others.' => '', // 1
/// TODO	'You will be able to have a geographical look on how the mess up all this time.' => '', // 1
/// TODO	'I intend to equip you with relevant tools to measure the quality of service you pay for.' => '', // 1

	// views/user/signup.tpl
/// TODO	'Name' => '', // 20
	'Language' => 'Langue', // 41
/// TODO	'English' => '', // 44
/// TODO	'French' => '', // 45
/// TODO	'Pidgin' => '', // 46

	// views/layout/footer.tpl
	'Fork us on GitHub!' => 'Cloner sur GitHub!', // 6
	'Feowl files under an Apache licence' => 'Le code source de Feowl est sous licence Apache', // 7
	'contact' => 'contact', // 11
	'blog' => 'blog', // 11
	'Feowl is financed by the <a href="http://www.freemedia.at/">International Press Institute</a>.' => 'Feowl est financé par le <a href="http://www.freemedia.at/">International Press Institute</a>.', // 15
	'It\'s a project by <a href="http://www.internetsansfrontieres.com/">Internet Sans Frontières</a>, <a href="http://jplusplus.org/">Journalism++</a>, <a href="http://www.tesobe.com/">Tesobe</a> and <a href="http://www.wasamundi.com/">Wasamundi</a>.' => 'Ce projet est mené  par <a href="http://www.internetsansfrontieres.com/">Internet Sans Frontières</a>, <a href="http://jplusplus.org/">Journalism++</a>, <a href="http://www.tesobe.com/">Tesobe</a> et <a href="http://www.wasamundi.com/">Wasamundi</a>.', // 18

	// views/layout/menu.tpl
	'Account' => 'Profil', // 16
	'Signup' => 'Inscription', // 23
	'Home' => 'Accueil', // 57
	'Explore' => 'Explorer', // 58
	'Contribute' => 'Contribuer', // 59

	// views/home/home.tpl
	'Legend' => 'Légende', // 12
	'No enough data' => 'Données insuffisantes', // 14
	'Less power cuts' => 'Peu de coupure', // 15
	'More power cuts' => 'Beaucoup de coupure', // 16
	'Welcome to Feowl' => 'Bienvenue sur Feowl	', // 31
	'<p>Feowl is a community-driven platform that produces accurate and actionable public data on the electricity supply in Douala.</p><p>Feowl will poll reliable voluntary contributors and will ask them about their power cut experience: Did they witness one? When was that? Where?</p><p>Feowl will aggregate, compute and analyze the data received via polls and will display them on this platform using the best visualization techniques.</p><p>Feowl was made possible thanks to a grant received from the International Press Institute.</p>' => '<p>Feowl est une plateforme alimentée par la communauté, qui produit des données publiques précises et exploitables sur la fourniture d\'électricité à Douala.</p><p>Feowl sondera des contributeurs volontaires fiables et leur posera des questions sur leur expérience des coupure de courant : en ont-ils subi une ? Quand était-ce ? Où était-ce ?</p><p>Feowl agrégera, calculera et analysera les données reçues via les sondages, et les disposera sur cette plateforme grâce aux meilleures techniques de visualisation en ligne.</p><p>Feowl a été rendu possible grâce un financement reçu de l\'Institut International de la Presse.</p>', // 32

	// views/explore/explore.tpl
	'Explore the data collected by Feowl' => 'Explorez les données collectées par Feowl', // 4
	'User reports' => 'Rapports des utilisateurs', // 27
	'District' => 'Arrondissement', // 31
	'Duration' => 'Durée', // 32
	'Date' => 'Date', // 33
	'Quality' => 'Qualité', // 34
	'Loading' => 'Chargement', // 47
	'Load more' => 'Voir plus', // 70
	'No reports submited for that period' => 'Aucun rapport soumis durant cette période', // 79

	// views/contribute/contribute.tpl
/// TODO	'Did you witness a power cut today ?' => '', // 1
/// TODO	'Yes' => '', // 1
/// TODO	'No' => '', // 1
/// TODO	'About when did it occur ?' => '', // 1
/// TODO	'Please select' => '', // 1
/// TODO	'Midnight' => '', // 1
/// TODO	'Midday' => '', // 1
/// TODO	'Please Select' => '', // 1
/// TODO	'How long did it last?' => '', // 1
/// TODO	'Less than 30Mins' => '', // 1
/// TODO	'About 30Mins' => '', // 1
/// TODO	'About 1 hour' => '', // 1
/// TODO	'About 2 hours' => '', // 1
/// TODO	'About 3 hours' => '', // 1
/// TODO	'Which part of town where you?' => '', // 1
/// TODO	'Douala I' => '', // 1
/// TODO	'Douala II' => '', // 1
/// TODO	'Douala III' => '', // 1
/// TODO	'Douala IV' => '', // 1
/// TODO	'Douala V' => '', // 1

	// views/contribute/how_to.tpl
/// TODO	'How to Contribute' => '', // 2
/// TODO	'Read More' => '', // 4

	// Orphan phrases
	'User Guide' => 'Guide Utilisateur',
	'Profile' => 'Profil',
	'Sign Out' => 'Déconnexion',
);
